version: "3"

services:

  runtime-setup:
    image: swift-http-structured-headers:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"
        ubuntu_version: "focal"

  unit-tests:
    image: swift-http-structured-headers:20.04-main

  test:
    image: swift-http-structured-headers:20.04-main
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: swift-http-structured-headers:20.04-main

