version: "3"

services:

  runtime-setup:
    image: swift-http-structured-headers:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  unit-tests:
    image: swift-http-structured-headers:22.04-5.10

  documentation-check:
    image: swift-http-structured-headers:22.04-5.10

  test:
    image: swift-http-structured-headers:22.04-5.10
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: swift-http-structured-headers:22.04-5.10

