# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1604.41.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-http-structured-headers:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-http-structured-headers:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  unit-tests:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -warnings-as-errors"

  test:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -warnings-as-errors $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"


  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
