version: "3"

services:

  runtime-setup:
    image: swift-http-structured-headers:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"
        ubuntu_version: "jammy"

  unit-tests:
    image: swift-http-structured-headers:22.04-5.9

  documentation-check:
    image: swift-http-structured-headers:22.04-5.9

  test:
    image: swift-http-structured-headers:22.04-5.9
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: swift-http-structured-headers:22.04-5.9

